### ISSUE TITLE
Not responding on commands

### ISSUE THREAD

**Issue by PvdGulik** [fdegier/homebridge-somfy-hotwired#12]
Hello, your instructions are very clear and really easy to follow!!
But it is not working...

I
◊ checked remote is working with battery
◊ checked the voltage between pin 1 (3,3V) and pin 9 one the Raspberry
◊ checked voltage drop on wire (up & down) soldered on the remote when using battery
◊ checked voltage small up on wire (my) soldered on the remote when using battery
◊ checked all connections (1,3,5,7,9) when connected on the raspberry
◊ checked homebridge log on altering button in HomeKit. Yes, it tells

> [16/08/2021, 21:24:42] [Zonnescherm] Closing shutters
> [16/08/2021, 21:24:54] [Zonnescherm] Operation completed!
> [16/08/2021, 21:24:54] [Zonnescherm] Opening shutters
> [16/08/2021,` 21:25:06] [Zonnescherm] Operation completed!

but no real closing and opening.

So what can be wrong...?
Looks exactly like issue "Don't Works for me #2". There you suggest must be something with power, but as said, I checked that

Any help is appreciated.

Thanks!

**Comment by F4stFr3ddy** [comment]
Hey,

How are you running Homebridge? Docker?

**Comment by PvdGulik** [comment]
Hello,

No Docker, just downloaded Homebridge Raspberry Pi image.

Thanks

**Comment by PvdGulik** [comment]
Could it be a rights problem (running Homebridge with sudo? 
I know from Hyperion that it needs sudo to use PWM. Is that needed for the Homebridge-Somfy-hotwired solution?

Thanks

**Comment by F4stFr3ddy** [comment]
I have it running with Docker, so it can be 2 things (assuming your wiring is correct)

1. I missed a dependency in the package
2. There is a package included in the Docker image that I did not list, or some other setting
3. Rights indeed. 

I checked my NPM packages in the container and don't see the usual suspects. So could you try sudo?

**Comment by PvdGulik** [comment]
Just another question before I try sudo command.

When the remote without battery connected to the Pi, using the buttons on the Somfy remote should work as well?

**Comment by F4stFr3ddy** [comment]
Yes, when you remove the battery and connect pin 1 and 9, you basically replaced the battery with permanent power.

**Comment by PvdGulik** [comment]
Oké, check. That works.
But when connected with the three other wires (3,5,7) it's not working. I'll check my soldering again of these three wires.

I soldered them on the pin of the button, left top. That's right isn't it? See picture![image](https://user-images.githubusercontent.com/9421474/129862430-41415e41-371a-43d8-aaf4-1d30f86d3e1d.jpeg)

**Comment by F4stFr3ddy** [comment]
What you can do is take a wire, connect it to black and touch the green, blue or yellow wire, if it then works your soldering is correct.

**Comment by PvdGulik** [comment]
Nope, when use with battery the don't work. So must be wrong pin then.
My remote looks little different from yours. How to find out which pin to use..

**Comment by PvdGulik** [comment]
When I short left and right of button, it response, but not when short to ground.

**Comment by F4stFr3ddy** [comment]
Which remote do you have?

**Comment by PvdGulik** [comment]
It's a Somfy Telis 1 RTS.
But I see, there are different types.

On the Board it has text:
Buttons side:
HA-X06
&
01 06

Battery sid:
5004805
&
ADR

The housing says:

Somfy
74300-France
Telis 1 RTS
Pure
1810630A01
Made in France
EN 186

**Comment by PvdGulik** [comment]
I found with battery inserted that:

Left "Up" button and Left "down" button have 3 volt when not pressed. For the "My" button it is on the right side 3 volt.
The otherside of the button have 0 V.

When I press the button, the 3 V drops to 0,3 volt, on both sides of the button of course.

**Comment by PvdGulik** [comment]
Tried on varios ways to short with ground, but never works. Only works when you short two pins of button.

So, is this a different type of remote?

And is there a way to get it working in your solution?

**Comment by F4stFr3ddy** [comment]
Usually there are a few spots (round bigger flats) that are called vcc, gnd and something else. 5 in total. Do you have those? Can you try shorting gnd to up down or my?

**Comment by PvdGulik** [comment]
That's what I did ;-). I check all spot, only one is GLD. Rest are all VCC or verry close by VCC.
All the button pin's I checked as well. All almost VCC (0.01 V less)

It only response when I short one pin with one of the pins of the button.

In the picture all found VCC. None of the pins of the button are directly connect to ground.![image](https://user-images.githubusercontent.com/9421474/129922280-42a0bcc2-ecb3-4828-bbcb-69a46f264caf.jpeg)

**Comment by PvdGulik** [comment]
As you can see, none of the button-pins are connected to the big green area of GND. So this must work different, I think

**Comment by PvdGulik** [comment]
I tried all pins of the switches to connect to GND. But no response. It must be a different implementation of a Telis 1 RTS.
Can you please help me to get it working?

Thanks!

**Comment by F4stFr3ddy** [comment]
I'm not sure how I can help you. I can confirm that it works with the following remotes, I always solder the wires to either the contacts or the switches themself. If you ground GND to UP/DOWN/MY it should work. Then you just solder the wires to those contacts and connect them to the GPIO.

Somfy Telis 1 RTS
![](https://knxgroothandel.nl/media/catalog/product/cache/e92a0b8c204cc647935998663cac6069/1/8/1810630.jpg)

Also the newer one:
![image](https://user-images.githubusercontent.com/13218917/130746074-e006efc5-a447-4394-be30-3d5b3167c0f9.png)

Somfy Wall:
![image](https://user-images.githubusercontent.com/13218917/130746112-b408f761-fe28-41bd-81bc-f482416ee4e6.png)

**Comment by PvdGulik** [comment]
Thanks for your reaction. I would like to know one thing:

If button not pressed, the voltage on one side is ~ 3.2 V, the other side 0 V
When you press the button, the voltage on both sides Goes to 0.3 V.

Is that in your case the same?

Thanks!

**Comment by F4stFr3ddy** [comment]
I will have to measure that at some point, first will have to buy a multimeter 😄. 

Is this the remote that you have? 

![image](https://user-images.githubusercontent.com/13218917/130763945-2c503aa1-433e-47f7-bf37-fecd20b696fb.png)

**Comment by PvdGulik** [comment]
Nope, I have this one:

![image](https://user-images.githubusercontent.com/9421474/130771420-8929c8c3-c50e-4329-a18d-6fe434c991f2.jpeg)

![image](https://user-images.githubusercontent.com/9421474/130771446-a799e31d-08ff-45a6-a5b3-ba3041dab71e.jpeg)

**Comment by F4stFr3ddy** [comment]
That is the exact same remote and board as I used in the README. While on your earlier pictures it was a different board.
