### ISSUE TITLE
Not working anymore on Hoobs-in-a-box Ver4

### ISSUE THREAD

**Issue by Armandl23** [fdegier/homebridge-somfy-hotwired#15]
Hello
My Somfy plugin was working ok and indeed (see hereunder for the explanation on why I state this) I had to open the casing of the Hoobs-in-a-Box to plug the Somfy remote.
After I upgraded to version 4.x the plugin claimed issues with GPIO.
A guy called Alex from Hoobs support tried to help me and eventually passed the hand to his developper who now replies that HIB doesn't support you plugin anymore
>>>>Hi Armand,

I have opened an issue on GitHub so our programmer team can review and comment on your problem.
https://github.com/hoobs-org/HOOBS/issues/1781 

Alex @ hoobs.org<<<
All details/logs/etc and the reply from the guys are in the above github link

What is your position?
Thanks
Vriendelijke groeten
Armand

**Comment by fdegier** [comment]
Hi,

Thanks for providing feedback. There are many options to run Homebridge and the biggest challenge is making sure that your installation has access to the GPIO. For my setup (Homebridge in Docker) it works by including the `rpio` package, however I can not support other setups alone. I think in this case it is an issue with `hoobs` if they identify the package I can add it to the project requirements. What do you think?

**Comment by Armandl23** [comment]
Hello
I choose HIB to make my “Non-Linux-knowledgeable” life easy. I can execute Terminal commands that are provided and managed to reinstall Hoobs from scratch on the SD when one update crashed.
Whatever you propose that meets meet my level of knowledge of a Linux environment and make my blinds work is OK for me.
Reinstalling HIB in Raspberry mode would force me to update afterwards all my IOS Shortcuts after reinstall of HIB.  Too cumbersome.

VG
Armand

**Comment by fdegier** [comment]
My suggestion, give it some time so the HIB team can identify the issue on their end. It worked before, they upgraded something which broke the communication between GPIO and Homebridge, correct?

Should they provide details on what package they support, e.g. not `rpio` then I can include that in the software.

**Comment by Armandl23** [comment]
Dag Fred
If you look at the link I provided to you they have perfectly identified the cause even if this cause doesn’t make sense to me here is the reply from the technician “HOOBS runs Debian, you need to follow the instructions for Debian not Raspberry Pi OS. I developed the OS with the knowledge that the GPIO pins were not accessible from outside the case.
Since this is using the GPIO pins, means the case was cracked open. This is OK, but it converts this from a managed solution to a DIY project.(…)”
What it stupid is that it did support GPIO in version3.
BR

**Comment by fdegier** [comment]
Raspberry Pi OS is also Debian based. 

You could run `sudo apt list --installed | grep pio` to see if packages for GPIO are installed. Most likely one is missing hence the plugin can not talk to it.

**Comment by Armandl23** [comment]
Hi
Here is the result of the command
__
sudo apt list --installed|grep pio

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cpio/stable,now 2.13+dfsg-4 armhf [installed]
python3-rpi.gpio/stable,now 0.7.0-0.2+b2 armhf [installed]
rpi.gpio-common/stable,now 0.7.0-0.2+b2 armhf [installed,automatic]
__
Armand
