### ISSUE TITLE
default_position suggestion

### ISSUE THREAD

**Issue by niky1989** [fdegier/homebridge-somfy-hotwired#16]
Is it possible to add other than "Up" and "Down"  "last state" under the default_position setting?

**Comment by fdegier** [comment]
Hey, I would love to have that but I am not sure if it's possible. 

The solution here is for a "dumb" product, its state is seen by a human and a human decides to change it, now we want to automate that, but we have no information about the actual state. If Homekit opens the shutter, but then a human closes it, this information is not passed back to Homekit (unless we add a physical sensor to the product). So therefore the initial thought was to have homekit upon reset just assume a default position and hope for the best.

I am unaware of a possibilities of using persistent storage in Homekit, if that is possible then I could integrate that to at least keep the state persisted during a reset. But then again, how often does one restart Homebridge?

What do you think?

**Comment by niky1989** [comment]
In my case I have the only remote is attached to the raspberry, so a human can't change it. And in the rare case that Raspberry need a restart and the blind is not in the correct position I need to manually adjust through the remote. This is why is suggest that addition. It is only a suggestion, I know that this case scenario is very rare.

**Comment by niky1989** [comment]
Mine doesn't always work, I don't know why, I will try again next restart.
